### ISSUE TITLE
Erro de mostrar estoque do produto

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/search-engine#85]
Na loja o produto tem estoque, mas ao pesquisar ele na loja na barra de pesquisa fala que não há
![Screenshot - 2021-06-04T121325 649](https://user-images.githubusercontent.com/35343551/120823894-4616d100-c52e-11eb-990f-d6f715a0f2d0.png)

Clicando nele:

![Screenshot - 2021-06-04T121440 915](https://user-images.githubusercontent.com/35343551/120824073-765e6f80-c52e-11eb-8192-9ef37604c09a.png)

Isso acontece tanto na loja, quanto no admin

**Comment by leomp12** [comment]
Essa lib é só cliente, certamente não é um issue daqui.
Você sabe quando isso foi alterado? Nesse momento a informação não foi mapeada no ELS, salve esses produtos novamente no painel que deve atualizar o banco.

**Comment by matheusgnreis** [comment]
Tem quase 40 minutos que foi alterado e na loja não teve mudança

**Comment by matheusgnreis** [comment]
A camila salvou de novo duas vezes segundo ela e não teve mudança

**Comment by leomp12** [comment]
Quem dera fosse só pra mostrar 😬 
Tava dando bosta mesmo quando era um produto que tinha variação e passou a não ter mais, corrigi e vou dar um bump em todos de todas as lojas no ELS mas isso demora um pouco, esse aí já está certo, se ela souber se mais algum só salvar no painel.
